### ISSUE TITLE
searx Agent support

### ISSUE THREAD

**Issue by ingenieroariel** [mpaepper/llm_agents#2]
Thanks for publishing this, I started to read the codebase for Marvin and langchain a few days ago and was in desperate need of something simpler.

If you take requests for agents I would like to kindly ask for searchx support. It can be self hosted, or given that searx is a python package even just imported to avoid the network call! By doing that we could have access to a lot of plugins like Github and Wolfram without writing all those agents.

**Comment by mpaepper** [comment]
Maybe you can write a pull request with a tool which implements searx?

Happy to add it then.
